// Create one self-contained worklet script so every dependency shares the
// distribution's cache/version URL. No top-level await, blob URLs, or fetch in
// AudioWorkletGlobalScope. Only synchronous wasm-bindgen initialization is used.
import { readFile, writeFile } from "node:fs/promises";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
const directory = resolve(process.argv[2]);
const web = fileURLToPath(new URL("../web/", import.meta.url));
let bindings = await readFile(join(directory, "tunes_web_dsp.js"), "utf8");
if (
  !bindings.includes("export class DspWorker") ||
  !bindings.includes("export { initSync, __wbg_init as default };")
)
  throw new Error(
    "Unexpected wasm-bindgen exports; update the worklet packager",
  );
bindings = bindings
  .replaceAll("export class ", "class ")
  .replaceAll("export function ", "function ")
  .replace("export { initSync, __wbg_init as default };", "");
// Only the WASM getrandom import uses this function in the generated glue.
bindings = bindings.replaceAll(
  "globalThis.crypto.getRandomValues(",
  "workletEntropy.fill(",
);
const entropy = (
  await readFile(join(web, "worklet-entropy.mjs"), "utf8")
).replace("export class ", "class ");
const encoder = (
  await readFile(join(web, "worklet-utf8.mjs"), "utf8")
).replaceAll("export class ", "class ");
const render = (await readFile(join(web, "render-buffer.mjs"), "utf8")).replace(
  "export function ",
  "function ",
);
const processor = (
  await readFile(join(web, "dsp-worklet.mjs"), "utf8")
).replace("export function ", "function ");
await writeFile(
  join(directory, "dsp-worklet.js"),
  `// Generated by package-worklet.mjs; do not edit.\n${encoder}\n${entropy}\nconst workletEntropy = new WorkletEntropy();\nconst bindings = (() => {\nconst TextEncoder = globalThis.TextEncoder ?? WorkletTextEncoder;\nconst TextDecoder = globalThis.TextDecoder ?? WorkletTextDecoder;\n${bindings}\nreturn { initSync, DspWorker };\n})();\n${render}\n${processor}\nregisterProcessor("tunes-dsp", createDspProcessor({ ...bindings, createBlockRenderer, entropy: workletEntropy }));\n`,
);
